//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kite.AutoTrading.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerOrder
    {
        public int Id { get; set; }
        public Nullable<int> JobId { get; set; }
        public string TradingSymbol { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Product { get; set; }
        public string OrderType { get; set; }
        public string Validity { get; set; }
        public Nullable<int> DisclosedQuantity { get; set; }
        public Nullable<decimal> TriggerPrice { get; set; }
        public Nullable<decimal> SquareOffValue { get; set; }
        public Nullable<decimal> StoplossValue { get; set; }
        public Nullable<decimal> TrailingStoploss { get; set; }
        public string Variety { get; set; }
        public string Tag { get; set; }
        public string OrderStatus { get; set; }
        public string StatusMessage { get; set; }
        public string BrokerOrderId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
