//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kite.AutoTrading.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerPosition
    {
        public decimal Id { get; set; }
        public string Exchange { get; set; }
        public string TradingSymbol { get; set; }
        public Nullable<decimal> Realised { get; set; }
        public Nullable<decimal> PNL { get; set; }
        public Nullable<decimal> AveragePrice { get; set; }
        public Nullable<decimal> Unrealised { get; set; }
        public Nullable<int> DayBuyQuantity { get; set; }
        public Nullable<int> DaySellQuantity { get; set; }
        public Nullable<decimal> DayBuyPrice { get; set; }
        public Nullable<decimal> DaySellPrice { get; set; }
        public Nullable<decimal> DayBuyValue { get; set; }
        public Nullable<decimal> DaySellValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
