//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kite.AutoTrading.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiteAutotradingEntities : DbContext
    {
        public KiteAutotradingEntities()
            : base("name=KiteAutotradingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Strategy> Strategies { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<Watchlist> Watchlists { get; set; }
        public virtual DbSet<Symbol> Symbols { get; set; }
        public virtual DbSet<WatchlistSymbolMapping> WatchlistSymbolMappings { get; set; }
        public virtual DbSet<BrokerOrder> BrokerOrders { get; set; }
        public virtual DbSet<BrokerPosition> BrokerPositions { get; set; }
    }
}
