//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kite.AutoTrading.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TradingSymbol { get; set; }
        public string InstrumentToken { get; set; }
        public string Exchange { get; set; }
        public string ExchangeToken { get; set; }
        public Nullable<decimal> TickSize { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string InstrumentType { get; set; }
        public string Segment { get; set; }
        public Nullable<decimal> Strike { get; set; }
        public Nullable<long> LotSize { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
