//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kite.AutoTrading.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int UserSessionId { get; set; }
        public string UserId { get; set; }
        public string ApiKey { get; set; }
        public string AppSecret { get; set; }
        public string AccessToken { get; set; }
        public string PublicToken { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
