//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kite.AutoTrading.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchlistSymbolMapping
    {
        public int Id { get; set; }
        public Nullable<int> WatchlistId { get; set; }
        public Nullable<int> SymbolId { get; set; }
    }
}
